Repository ORNL/GridKit, pull requests merged in 2024-12, with the labels that each got.

#35 Forward compatibility with SUNDIALS
  CMakeLists.txt
  README.md
  Solver/Dynamic/Ida.cpp
  Solver/Dynamic/Ida.hpp
  Solver/Optimization/DynamicConstraint.cpp
  Solver/SteadyState/Kinsol.cpp
  Solver/SteadyState/Kinsol.hpp
Labels: enhancement

#30 BugFix: Scale Microgrid Error
  Examples/ScaleMicrogrid/ScaleMicrogrid.cpp
  Examples/ScaleMicrogrid/SolutionKeys.hpp
Labels: bug

#5 Add brief style guidelines.
  CONTRIBUTING.md
Labels: documentation

#37 Fixed IDA Interface Final Copy
  Examples/ScaleMicrogrid/CMakeLists.txt
  Examples/ScaleMicrogrid/ScaleMicrogrid.cpp
  Examples/ScaleMicrogrid/SolutionKeys.hpp
  Solver/Dynamic/Ida.cpp
Labels: bug
