Repository ORNL/GridKit, pull requests merged in 2025-04, with the labels that each got.

#84 Add PR and issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/build_error.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/test_error.yml
  .github/pull_request_template.md
  README.md
Labels: development

#69 Example using enzyme-auto-sparsity
  .github/workflows/spack_default_build.yaml
  cmake/FindEnzyme.cmake
  examples/Enzyme/Standalone/CMakeLists.txt
  examples/Enzyme/Standalone/EnzymeSparse.cpp
Labels: development, automatic differentiation

#90 Added back removed test for N=8
  examples/ScaleMicrogrid/ScaleMicrogrid.cpp
Labels: enhancement, testing

#93 Add input format specifications for phasor dynamics models
  src/Model/PhasorDynamics/INPUT_FORMAT.md
Labels: documentation
