Repository ORNL/GridKit, pull requests merged in 2025-02, with the labels that each got.

#48 Improve the way to find Enzyme.
  cmake/FindEnzyme.cmake
Labels: cmake

#42 Aligning the code with contributing guidelines
  examples/Grid3Bus/README.md
  examples/Microgrid/Microgrid.cpp
  examples/RLCircuit/RLCircuit.cpp
  examples/ScaleMicrogrid/ScaleMicrogrid.cpp
  examples/ScaleMicrogrid/SolutionKeys.hpp
  examples/SparseTest/SparseTest.cpp
  src/CircuitGraph.hpp
  src/LinearAlgebra/COO_Matrix.hpp
  src/Model/PowerElectronics/Capacitor/Capacitor.cpp
  src/Model/PowerElectronics/Capacitor/Capacitor.hpp
  src/Model/PowerElectronics/CircuitComponent.hpp
  src/Model/PowerElectronics/DistributedGenerator/DistributedGenerator.cpp
  src/Model/PowerElectronics/DistributedGenerator/DistributedGenerator.hpp
  src/Model/PowerElectronics/InductionMotor/InductionMotor.cpp
  src/Model/PowerElectronics/InductionMotor/InductionMotor.hpp
  src/Model/PowerElectronics/Inductor/Inductor.cpp
  src/Model/PowerElectronics/Inductor/Inductor.hpp
  src/Model/PowerElectronics/LinearTransformer/LinearTransformer.cpp
  src/Model/PowerElectronics/LinearTransformer/LinearTransformer.hpp
  src/Model/PowerElectronics/MicrogridBusDQ/MicrogridBusDQ.cpp
  src/Model/PowerElectronics/MicrogridBusDQ/MicrogridBusDQ.hpp
  src/Model/PowerElectronics/MicrogridLine/MicrogridLine.cpp
  src/Model/PowerElectronics/MicrogridLine/MicrogridLine.hpp
  src/Model/PowerElectronics/MicrogridLoad/MicrogridLoad.cpp
  src/Model/PowerElectronics/MicrogridLoad/MicrogridLoad.hpp
  src/Model/PowerElectronics/Resistor/Resistor.cpp
  src/Model/PowerElectronics/Resistor/Resistor.hpp
  src/Model/PowerElectronics/SynchronousMachine/SynchronousMachine.cpp
  src/Model/PowerElectronics/SynchronousMachine/SynchronousMachine.hpp
  src/Model/PowerElectronics/SystemModelPowerElectronics.hpp
  src/Model/PowerElectronics/TransmissionLine/TransmissionLine.cpp
  src/Model/PowerElectronics/TransmissionLine/TransmissionLine.hpp
  src/Model/PowerElectronics/VoltageSource/VoltageSource.cpp
  src/Model/PowerElectronics/VoltageSource/VoltageSource.hpp
  src/Model/PowerFlow/Bus/BaseBus.hpp
  src/Model/PowerFlow/Bus/BusSlack.hpp
  src/Model/PowerFlow/MiniGrid/MiniGrid.cpp
  src/Model/PowerFlow/MiniGrid/MiniGrid.hpp
  src/Model/PowerFlow/SystemModelPowerFlow.hpp
  src/ModelEvaluator.hpp
  src/ModelEvaluatorImpl.hpp
  src/Solver/Dynamic/Ida.cpp
  src/SystemModel.hpp
Labels: documentation, enhancement

#58 Fix include issue with Branch.hpp (#57)
  src/Model/PowerFlow/Branch/Branch.hpp
Labels: bug

#63 Add dependency-tracking variable data type.
  src/LinearAlgebra/SparsityPattern/Variable.hpp
  src/LinearAlgebra/SparsityPattern/VariableImplementation.hpp
  src/LinearAlgebra/SparsityPattern/VariableOperators.hpp
  src/Utilities/Testing.hpp
  tests/UnitTests/CMakeLists.txt
  tests/UnitTests/SparsityPattern/CMakeLists.txt
  tests/UnitTests/SparsityPattern/SparsityPatternTests.hpp
  tests/UnitTests/SparsityPattern/runSparsityPatternTests.cpp
Labels: enhancement
