Repository ORNL/GridKit, pull requests merged in 2025-07, with the labels that each got.

#60 Improving Documentation of Microgrid and Components
  examples/PowerElectronics/Microgrid/README.md
  examples/PowerElectronics/ScaleMicrogrid/README.md
  src/Model/PowerElectronics/DistributedGenerator/README.md
  src/Model/PowerElectronics/MicrogridBusDQ/README.md
  src/Model/PowerElectronics/MicrogridLine/README.md
  src/Model/PowerElectronics/MicrogridLoad/README.md
  src/Model/PowerElectronics/README.md
Labels: documentation

#184 Use interface target to link to component models
  CMakeLists.txt
  examples/PhasorDynamics/Small/TenGen/Classical/CMakeLists.txt
  examples/PhasorDynamics/Small/TenGen/Classical/TenGenClassical.cpp
  examples/PhasorDynamics/Small/TenGen/Genrou/CMakeLists.txt
  examples/PhasorDynamics/Small/TenGen/Genrou/TenGenGenrou.cpp
  examples/PhasorDynamics/Tiny/ThreeBus/Basic/CMakeLists.txt
  examples/PhasorDynamics/Tiny/ThreeBus/Basic/ThreeBusBasic.cpp
  examples/PhasorDynamics/Tiny/ThreeBus/Classical/CMakeLists.txt
  examples/PhasorDynamics/Tiny/ThreeBus/Classical/ThreeBusClassical.cpp
  examples/PhasorDynamics/Tiny/TwoBus/Basic/CMakeLists.txt
  examples/PhasorDynamics/Tiny/TwoBus/Basic/TwoBusBasic.cpp
  examples/PhasorDynamics/Tiny/TwoBus/Tgov1/CMakeLists.txt
  examples/PhasorDynamics/Tiny/TwoBus/Tgov1/TwoBusTgov1.cpp
  src/Model/PhasorDynamics/Branch/CMakeLists.txt
  src/Model/PhasorDynamics/Bus/CMakeLists.txt
  src/Model/PhasorDynamics/BusFault/CMakeLists.txt
  src/Model/PhasorDynamics/CMakeLists.txt
  src/Model/PhasorDynamics/ComponentLibrary.hpp
  src/Model/PhasorDynamics/Governor/Tgov1/CMakeLists.txt
  src/Model/PhasorDynamics/Load/CMakeLists.txt
  src/Model/PhasorDynamics/SynchronousMachine/GENROUwS/CMakeLists.txt
  src/Model/PhasorDynamics/SynchronousMachine/GenClassical/CMakeLists.txt
  tests/UnitTests/PhasorDynamics/CMakeLists.txt
Labels: enhancement, good first issue, cmake

#182 system jacobian testing for phasor dynamics models
  src/Model/PhasorDynamics/BusFault/BusFault.cpp
  src/Model/PhasorDynamics/BusFault/BusFaultDependencyTracking.cpp
  src/Model/PhasorDynamics/BusFault/BusFaultImpl.hpp
  src/Model/PhasorDynamics/BusFault/CMakeLists.txt
  src/Model/PhasorDynamics/Component.hpp
  src/Model/PhasorDynamics/Load/LoadImpl.hpp
  src/Model/PhasorDynamics/SynchronousMachine/GENROUwS/CMakeLists.txt
  src/Model/PhasorDynamics/SynchronousMachine/GENROUwS/Genrou.cpp
  src/Model/PhasorDynamics/SynchronousMachine/GENROUwS/Genrou.hpp
  src/Model/PhasorDynamics/SynchronousMachine/GENROUwS/GenrouDependencyTracking.cpp
  src/Model/PhasorDynamics/SynchronousMachine/GENROUwS/GenrouImpl.hpp
  tests/UnitTests/PhasorDynamics/CMakeLists.txt
  tests/UnitTests/PhasorDynamics/SystemTests.hpp
  tests/UnitTests/PhasorDynamics/runSystemTests.cpp
Labels: automatic differentiation

#192 Exciter Implementation and Example
  examples/PhasorDynamics/Tiny/ThreeBus/Basic/ThreeBusBasic.cpp
  examples/PhasorDynamics/Tiny/TwoBus/CMakeLists.txt
  examples/PhasorDynamics/Tiny/TwoBus/Ieeet1/CMakeLists.txt
  examples/PhasorDynamics/Tiny/TwoBus/Ieeet1/TwoBusIeeet1.cpp
  examples/PhasorDynamics/Tiny/TwoBus/Ieeet1/TwoBusIeeet1.hpp
  src/Model/PhasorDynamics/CMakeLists.txt
  src/Model/PhasorDynamics/ComponentLibrary.hpp
  src/Model/PhasorDynamics/Exciter/CMakeLists.txt
  src/Model/PhasorDynamics/Exciter/IEEET1/CMakeLists.txt
  src/Model/PhasorDynamics/Exciter/IEEET1/Ieeet1.cpp
  src/Model/PhasorDynamics/Exciter/IEEET1/Ieeet1.hpp
  src/Model/PhasorDynamics/Exciter/IEEET1/Ieeet1Data.hpp
  src/Model/PhasorDynamics/Exciter/IEEET1/README.md
  src/Model/PhasorDynamics/Exciter/README.md
  src/Model/PhasorDynamics/INPUT_FORMAT.md
  src/Model/PhasorDynamics/SynchronousMachine/GENROUwS/Genrou.hpp
  src/Model/PhasorDynamics/SynchronousMachine/GENROUwS/GenrouImpl.hpp
  src/Model/PhasorDynamics/SystemModelData.hpp
Labels: new model

#202 improvements to the component signal object and json parser infrastructure
  src/Model/PhasorDynamics/Bus/BusDataJSONParser.hpp
  src/Model/PhasorDynamics/ComponentDataJSONParser.hpp
  src/Model/PhasorDynamics/ComponentSignals.hpp
  src/Model/PhasorDynamics/SystemModelDataJSONParser.hpp
Labels: documentation, enhancement
