Repository ORNL/GridKit, pull requests merged in 2025-01, with the labels that each got.

#40 Fix runtime path setting when using clang++ and gfortran compilers
  CMakeLists.txt
  Examples/DynamicConstrainedOpt/CMakeLists.txt
  Examples/GenConstLoad/CMakeLists.txt
  Examples/GenInfiniteBus/CMakeLists.txt
  Examples/ParameterEstimation/CMakeLists.txt
Labels: bug, cmake

#44 Fixes input file issue with parameter estimation example
  .gitignore
  ComponentLib/PowerFlow/Bus/BaseBus.hpp
  ComponentLib/PowerFlow/Bus/BusPQ.hpp
  ComponentLib/PowerFlow/Bus/BusPV.hpp
  ComponentLib/PowerFlow/Bus/BusSlack.hpp
  ComponentLib/PowerFlow/Generator4Param/static_data.hpp
  Examples/ParameterEstimation/CMakeLists.txt
  Examples/ParameterEstimation/ParameterEstimation.cpp
  Examples/ParameterEstimation/lookup_table.hpp
  Utilities/FileIO.hpp
Labels: bug, testing

#46 Fix lookup install and downgrade to LLVM 16
  .github/workflows/spack_default_build.yaml
  Examples/ParameterEstimation/CMakeLists.txt
  README.md
Labels: bug

#50 Fix figure paths in README files
  src/Model/PhasorDynamics/Branch/README.md
  src/Model/PhasorDynamics/Bus/README.md
  src/Model/PhasorDynamics/Exciter/README.md
  src/Model/PhasorDynamics/Governor/README.md
  src/Model/PhasorDynamics/Stabilizer/README.md
  src/Model/PhasorDynamics/SynchronousMachine/GENROUwS/README.md
  src/Model/PhasorDynamics/SynchronousMachine/GENSALwS/README.md
  src/Model/PhasorDynamics/SynchronousMachine/README.md
  src/Model/PowerFlow/Branch/README.md
  src/Model/PowerFlow/Bus/README.md
Labels: documentation

#52 Install documentation update for Suitesparse and SUNDIALS
  README.md
Labels: documentation
