Repository ORNL/GridKit, pull requests merged in 2025-05, with the labels that each got.

#88 Lukel/phasor docs
  src/Model/PhasorDynamics/SynchronousMachine/GENROUwS/README.md
  src/Model/PhasorDynamics/SynchronousMachine/GENSALwS/README.md
  src/Model/PhasorDynamics/SynchronousMachine/README.md
Labels: documentation

#85 Unit test and example for `Genrou` class.
  examples/DistributedGeneratorTest/DGTest.cpp
  examples/Grid3Bus/Grid3BusSys.cpp
  examples/Microgrid/Microgrid.cpp
  examples/PhasorDynamics/CMakeLists.txt
  examples/PhasorDynamics/Example1/CMakeLists.txt
  examples/PhasorDynamics/Example1/example1.cpp
  examples/PhasorDynamics/Example1/example1.hpp
  examples/PhasorDynamics/Example2/CMakeLists.txt
  examples/PhasorDynamics/Example2/example2.cpp
  examples/PhasorDynamics/Example2/example2.hpp
  examples/ScaleMicrogrid/ScaleMicrogrid.cpp
  src/Model/PhasorDynamics/Load/Load.cpp
  src/Model/PhasorDynamics/Load/README.md
  src/Model/PhasorDynamics/SynchronousMachine/GENROUwS/Genrou.cpp
  src/Model/PowerElectronics/SynchronousMachine/SynchronousMachine.cpp
  src/Model/PowerFlow/Generator2/Generator2.cpp
  src/Model/PowerFlow/Generator4/Generator4.cpp
  src/Model/PowerFlow/Generator4Governor/Generator4Governor.cpp
  src/Model/PowerFlow/Generator4Param/Generator4Param.cpp
  tests/UnitTests/PhasorDynamics/GenrouTests.hpp
  tests/UnitTests/PhasorDynamics/LoadTests.hpp
Labels: enhancement, testing

#99 Update developer guidelines with Doxygen instructions
  CONTRIBUTING.md
Labels: documentation

#106 Fixes to assertions and overrides
  examples/PhasorDynamics/Example1/example1.cpp
  examples/PhasorDynamics/Example1/example1.hpp
  examples/PhasorDynamics/Example2/example2.cpp
  examples/PhasorDynamics/Example2/example2.hpp
  src/Solver/Optimization/DynamicConstraint.cpp
  src/Solver/Optimization/DynamicObjective.cpp
  tests/UnitTests/Solver/Dynamic/IdaTests.hpp
Labels: bug

#89 Verify Branch and Load Jacobians computed with Sparse::Variable
  src/LinearAlgebra/SparsityPattern/Variable.hpp
  src/Model/PhasorDynamics/Branch/Branch.cpp
  src/Model/PhasorDynamics/Bus/Bus.cpp
  src/Model/PhasorDynamics/Bus/BusInfinite.cpp
  src/Model/PhasorDynamics/BusBase.hpp
  src/Model/PhasorDynamics/Component.hpp
  src/Model/PhasorDynamics/Load/Load.cpp
  src/Utilities/Testing.hpp
  tests/UnitTests/PhasorDynamics/BranchTests.hpp
  tests/UnitTests/PhasorDynamics/LoadTests.hpp
  tests/UnitTests/PhasorDynamics/runBranchTests.cpp
  tests/UnitTests/PhasorDynamics/runLoadTests.cpp
Labels: development, testing, automatic differentiation

#108 Fix load Jacobian
  .github/workflows/spack_default_build.yaml
  tests/UnitTests/PhasorDynamics/LoadTests.hpp
Labels: bug

#111 Minor suggestions to SUNDIALS interface
  examples/PowerElectronics/RLCircuit/RLCircuit.cpp
  src/Solver/Dynamic/Ida.cpp
  src/Solver/Dynamic/Ida.hpp
Labels: enhancement

#114 Move `PowerSystemsData.hpp` and `CircuitGraph.hpp` to correct subdirectories
  examples/PowerFlow/Grid3Bus/Grid3BusSys.cpp
  examples/PowerFlow/MatPowerTesting/MatPowerTesting.hpp
  examples/PowerFlow/MatPowerTesting/test_parse_branch_row.cpp
  examples/PowerFlow/MatPowerTesting/test_parse_bus_row.cpp
  examples/PowerFlow/MatPowerTesting/test_parse_gen_row.cpp
  examples/PowerFlow/MatPowerTesting/test_parse_gencost_row.cpp
  examples/PowerFlow/MatPowerTesting/test_parse_matpower.cpp
  src/Model/PhasorDynamics/Branch/Branch.cpp
  src/Model/PhasorDynamics/Bus/Bus.cpp
  src/Model/PhasorDynamics/Bus/BusInfinite.cpp
  src/Model/PhasorDynamics/BusFault/BusFault.cpp
  src/Model/PhasorDynamics/Load/Load.cpp
  src/Model/PowerElectronics/Capacitor/Capacitor.hpp
  src/Model/PowerElectronics/CircuitComponent.hpp
  src/Model/PowerElectronics/CircuitGraph.hpp
  src/Model/PowerElectronics/DistributedGenerator/DistributedGenerator.hpp
  src/Model/PowerElectronics/InductionMotor/InductionMotor.hpp
  src/Model/PowerElectronics/Inductor/Inductor.hpp
  src/Model/PowerElectronics/LinearTransformer/LinearTransformer.hpp
  src/Model/PowerElectronics/MicrogridBusDQ/MicrogridBusDQ.hpp
  src/Model/PowerElectronics/MicrogridLine/MicrogridLine.hpp
  src/Model/PowerElectronics/MicrogridLoad/MicrogridLoad.hpp
  src/Model/PowerElectronics/Resistor/Resistor.hpp
  src/Model/PowerElectronics/SynchronousMachine/SynchronousMachine.hpp
  src/Model/PowerElectronics/SystemModelPowerElectronics.hpp
  src/Model/PowerElectronics/TransmissionLine/TransmissionLine.hpp
  src/Model/PowerElectronics/VoltageSource/VoltageSource.hpp
  src/Model/PowerFlow/Branch/Branch.cpp
  src/Model/PowerFlow/Bus/BusFactory.hpp
  src/Model/PowerFlow/Bus/BusPQ.hpp
  src/Model/PowerFlow/Bus/BusPV.hpp
  src/Model/PowerFlow/Bus/BusSlack.hpp
  src/Model/PowerFlow/Generator/GeneratorFactory.hpp
  src/Model/PowerFlow/Generator/GeneratorPQ.hpp
  src/Model/PowerFlow/Generator/GeneratorPV.hpp
  src/Model/PowerFlow/Generator/GeneratorSlack.hpp
  src/Model/PowerFlow/Load/Load.hpp
  src/Model/PowerFlow/MatpowerParser.hpp
  src/Model/PowerFlow/PowerSystemData.hpp
  src/Utilities/FileIO.hpp
Labels: enhancement, good first issue

#121 Only check c/c++ files with clang-format pre-commit
  .pre-commit-config.yaml
Labels: development

#86 Add dev container
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  CONTRIBUTING.md
Labels: good first issue, development

#117 fix a memory leak, add asan / ubsan support to the cmake configuration
  .editorconfig
  CMakeLists.txt
  examples/LinearAlgebra/SparseTest/SparseTest.cpp
  examples/PowerElectronics/DistributedGeneratorTest/DGTest.cpp
  src/Model/PowerElectronics/SynchronousMachine/SynchronousMachine.cpp
  src/Model/PowerFlow/Generator4Param/Generator4Param.cpp
Labels: bug, development, cmake

#116 Create phasor dynamics model data structures (take two)
  examples/PowerFlow/Grid3Bus/Grid3BusSys.cpp
  examples/PowerFlow/MatPowerTesting/MatPowerTesting.hpp
  examples/PowerFlow/MatPowerTesting/test_parse_branch_row.cpp
  examples/PowerFlow/MatPowerTesting/test_parse_bus_row.cpp
  examples/PowerFlow/MatPowerTesting/test_parse_gen_row.cpp
  examples/PowerFlow/MatPowerTesting/test_parse_gencost_row.cpp
  examples/PowerFlow/MatPowerTesting/test_parse_matpower.cpp
  src/Model/PhasorDynamics/Branch/Branch.cpp
  src/Model/PhasorDynamics/Branch/Branch.hpp
  src/Model/PhasorDynamics/Branch/BranchData.hpp
  src/Model/PhasorDynamics/Bus/Bus.cpp
  src/Model/PhasorDynamics/Bus/Bus.hpp
  src/Model/PhasorDynamics/Bus/BusData.hpp
  src/Model/PhasorDynamics/Bus/BusInfinite.cpp
  src/Model/PhasorDynamics/Bus/BusInfinite.hpp
  src/Model/PhasorDynamics/BusFault/BusFault.cpp
  src/Model/PhasorDynamics/Load/Load.cpp
  src/Model/PhasorDynamics/Load/Load.hpp
  src/Model/PhasorDynamics/Load/LoadData.hpp
  src/Model/PowerElectronics/SynchronousMachine/SynchronousMachine.cpp
  src/Model/PowerFlow/Branch/Branch.cpp
  src/Model/PowerFlow/Branch/Branch.hpp
  src/Model/PowerFlow/Bus/BusFactory.hpp
  src/Model/PowerFlow/Bus/BusPQ.hpp
  src/Model/PowerFlow/Bus/BusPV.hpp
  src/Model/PowerFlow/Bus/BusSlack.hpp
  src/Model/PowerFlow/Generator/GeneratorFactory.hpp
  src/Model/PowerFlow/Generator/GeneratorPQ.hpp
  src/Model/PowerFlow/Generator/GeneratorPV.hpp
  src/Model/PowerFlow/Generator/GeneratorSlack.hpp
  src/Model/PowerFlow/Generator4Param/Generator4Param.cpp
  src/Model/PowerFlow/Load/Load.hpp
  src/Model/PowerFlow/MatpowerParser.hpp
  src/Model/PowerFlow/PowerFlowData.hpp
  src/Model/PowerFlow/SystemModelPowerFlow.hpp
Labels: enhancement, new model
